version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "type:dependencies"
      - "language:kotlin"
    commit-message:
      prefix: "chore(deps): "
